//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Antécedant
    {
        public int numA { get; set; }
        public string nomA { get; set; }
        public Nullable<System.DateTime> dateD { get; set; }
        public string traiter { get; set; }
        public string Observation { get; set; }
        public string patient { get; set; }
    
        public virtual patient patient1 { get; set; }
    }
}
