//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichierMédical
    {
        public int numF { get; set; }
        public string typeF { get; set; }
        public byte[] imageF { get; set; }
        public Nullable<int> visite { get; set; }
        public string Observation { get; set; }
    
        public virtual visite visite1 { get; set; }
    }
}
