//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public patient()
        {
            this.Antécedant = new HashSet<Antécedant>();
            this.RDVs = new HashSet<RDV>();
        }
    
        public string numP { get; set; }
        public string nomP { get; set; }
        public string prénomP { get; set; }
        public string sexe { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        public string télèphone { get; set; }
        public string situationF { get; set; }
        public string mutuelle { get; set; }
        public string adresse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antécedant> Antécedant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDV> RDVs { get; set; }
    }
}
