//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDV
    {
        public int numR { get; set; }
        public Nullable<System.DateTime> dateR { get; set; }
        public string heure { get; set; }
        public string motifR { get; set; }
        public Nullable<int> visite { get; set; }
        public string patient { get; set; }
    
        public virtual patient patient1 { get; set; }
        public virtual visite visite1 { get; set; }
    }
}
