//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.WinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class visite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visite()
        {
            this.FichierMédical = new HashSet<FichierMédical>();
            this.payements = new HashSet<payement>();
            this.RDVs = new HashSet<RDV>();
        }
    
        public int numV { get; set; }
        public string Examen { get; set; }
        public string Conclusion { get; set; }
        public string traitement { get; set; }
        public string motif { get; set; }
        public Nullable<double> montant { get; set; }
        public Nullable<bool> payé { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FichierMédical> FichierMédical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payement> payements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDV> RDVs { get; set; }
    }
}
